#!/bin/bash

HOSTNAME=$(hostname -s)

#get certs and config generated by master-1 on shared folder
cd /vagrant/ubuntu/lab_automation/CA

cd $HOME
FILE=ca.crt
if [[ ! -f "$FILE" ]]; then
    cp /vagrant/ubuntu/lab_automation/CA/${FILE} $HOME/
fi

FILE=admin.crt
if [[ ! -f "$FILE" ]]; then
    cp /vagrant/ubuntu/lab_automation/CA/${FILE} $HOME/
fi

FILE=admin.key
if [[ ! -f "$FILE" ]]; then
    cp /vagrant/ubuntu/lab_automation/CA/${FILE} $HOME/
fi

# Generate a kubeconfig file suitable for authenticating as the admin user
{
  KUBERNETES_LB_ADDRESS=192.168.5.30

  kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.crt \
    --embed-certs=true \
    --server=https://${KUBERNETES_LB_ADDRESS}:6443

  kubectl config set-credentials admin \
    --client-certificate=admin.crt \
    --client-key=admin.key

  kubectl config set-context kubernetes-the-hard-way \
    --cluster=kubernetes-the-hard-way \
    --user=admin

  kubectl config use-context kubernetes-the-hard-way
}

